### PR TITLE
dsch/Filter Component: added checkbox component, chakra added & removal, added react icons

### PR DESCRIPTION
**Pull request by dschreiter**
- react icons
- chakra 
- try out chakra lib.

### CODE REVIEW

**Review by Natedaug — APPROVED** [review]
good work bucks

**Comment by dschreiter** [comment]
- Removal of Chakra & it's dependencies, to much additional markup
- creation of custom Checkbox comp.

**Review by Natedaug — APPROVED** [review]

**Review by dschreiter — COMMENTED** [review]
looks good, feature branches to follow ...

**Comment by dschreiter** [comment]
These changes already exist on feature branches created downstream off of DEV, as a result it can be closed.

**Pull request closed without merging**
